# config/settings.yaml

# Data paths
data:
  raw_path: data/healthcare_claims.csv
  processed_path: data/health_claims_cleaned.csv

# Model save location
model:
  save_path: models/cat_boost_model.pkl

# Train/Test split configuration
train_test_split:
  test_size: 0.2
  random_state: 42
  stratify: true

# Cross-validation configuration
cross_validation:
  n_splits: 5
  random_state: 42
  shuffle: true

# CatBoost hyperparameters for GridSearchCV
catboost_params:
  model__iterations: [100, 200]
  model__learning_rate: [0.1, 0.15]
  model__depth: [5, 7]
